/**
 * @file oauth_clients_info.h
 * @brief OAuth 客户端注册表
 * @note Auto-generated by ORM code generator. DO NOT MODIFY.
 */
#pragma once

#include <vector>

#include <chen/db/db.h>
#include <chen/util/util.h>

namespace auth {
namespace data {

class OauthClientsInfoDao;
class OauthClientsInfo {
friend class OauthClientsInfoDao;
public:
    typedef std::shared_ptr<OauthClientsInfo> ptr;

    OauthClientsInfo();

    const int64_t& getId() { return m_id; }
    void setId(const int64_t& v);

    const std::string& getClientId() { return m_clientId; }
    void setClientId(const std::string& v);

    const std::string& getClientSecretHash() { return m_clientSecretHash; }
    void setClientSecretHash(const std::string& v);

    const std::string& getClientName() { return m_clientName; }
    void setClientName(const std::string& v);

    const std::string& getRedirectUris() { return m_redirectUris; }
    void setRedirectUris(const std::string& v);

    const std::string& getGrantTypes() { return m_grantTypes; }
    void setGrantTypes(const std::string& v);

    const std::string& getAllowedScopes() { return m_allowedScopes; }
    void setAllowedScopes(const std::string& v);

    const std::string& getClientUri() { return m_clientUri; }
    void setClientUri(const std::string& v);

    const std::string& getLogoUri() { return m_logoUri; }
    void setLogoUri(const std::string& v);

    const int32_t& getEnabled() { return m_enabled; }
    void setEnabled(const int32_t& v);

    const int64_t& getCreateTime() { return m_createTime; }
    void setCreateTime(const int64_t& v);

    const int64_t& getUpdateTime() { return m_updateTime; }
    void setUpdateTime(const int64_t& v);

    std::string toJsonString() const;

private:
    int32_t m_enabled;
    int64_t m_id;
    std::string m_clientId;
    std::string m_clientSecretHash;
    std::string m_clientName;
    std::string m_grantTypes;
    std::string m_allowedScopes;
    std::string m_clientUri;
    std::string m_logoUri;
    std::string m_redirectUris;
    int64_t m_createTime;
    int64_t m_updateTime;
};


class OauthClientsInfoDao {
public:
    typedef std::shared_ptr<OauthClientsInfoDao> ptr;
    static int Update(OauthClientsInfo::ptr info, chen::IDB::ptr conn);
    static int Insert(OauthClientsInfo::ptr info, chen::IDB::ptr conn);
    static int InsertOrUpdate(OauthClientsInfo::ptr info, chen::IDB::ptr conn);
    static int Delete(OauthClientsInfo::ptr info, chen::IDB::ptr conn);
    static int Delete(const int64_t& id, chen::IDB::ptr conn);
    static int DeleteById( const int64_t& id, chen::IDB::ptr conn);
    static int DeleteByClientId( const std::string& client_id, chen::IDB::ptr conn);
    static int QueryAll(std::vector<OauthClientsInfo::ptr>& results, chen::IDB::ptr conn);
    static OauthClientsInfo::ptr Query( const int64_t& id, chen::IDB::ptr conn);
    static OauthClientsInfo::ptr QueryByClientId( const std::string& client_id, chen::IDB::ptr conn);
    static int CreateTableSQLite3(chen::IDB::ptr info);
    static int CreateTableMySQL(chen::IDB::ptr info);
    static int MigrateTableSQLite3(chen::IDB::ptr info);
    static int MigrateTableMySQL(chen::IDB::ptr info);
};

} //namespace data
} //namespace auth
