/**
 * @file oauth_users_info.h
 * @brief OIDC 用户表
 * @note Auto-generated by ORM code generator. DO NOT MODIFY.
 */
#pragma once

#include <vector>

#include <chen/db/db.h>
#include <chen/util/util.h>

namespace auth {
namespace data {

class OauthUsersInfoDao;
class OauthUsersInfo {
friend class OauthUsersInfoDao;
public:
    typedef std::shared_ptr<OauthUsersInfo> ptr;

    OauthUsersInfo();

    const int64_t& getId() { return m_id; }
    void setId(const int64_t& v);

    const std::string& getUsername() { return m_username; }
    void setUsername(const std::string& v);

    const std::string& getEmail() { return m_email; }
    void setEmail(const std::string& v);

    const std::string& getPasswordHash() { return m_passwordHash; }
    void setPasswordHash(const std::string& v);

    const std::string& getDisplayName() { return m_displayName; }
    void setDisplayName(const std::string& v);

    const std::string& getAvatarUrl() { return m_avatarUrl; }
    void setAvatarUrl(const std::string& v);

    const int32_t& getEmailVerified() { return m_emailVerified; }
    void setEmailVerified(const int32_t& v);

    const int32_t& getEnabled() { return m_enabled; }
    void setEnabled(const int32_t& v);

    const int64_t& getCreateTime() { return m_createTime; }
    void setCreateTime(const int64_t& v);

    const int64_t& getUpdateTime() { return m_updateTime; }
    void setUpdateTime(const int64_t& v);

    std::string toJsonString() const;

private:
    int32_t m_emailVerified;
    int32_t m_enabled;
    int64_t m_id;
    std::string m_username;
    std::string m_email;
    std::string m_passwordHash;
    std::string m_displayName;
    std::string m_avatarUrl;
    int64_t m_createTime;
    int64_t m_updateTime;
};


class OauthUsersInfoDao {
public:
    typedef std::shared_ptr<OauthUsersInfoDao> ptr;
    static int Update(OauthUsersInfo::ptr info, chen::IDB::ptr conn);
    static int Insert(OauthUsersInfo::ptr info, chen::IDB::ptr conn);
    static int InsertOrUpdate(OauthUsersInfo::ptr info, chen::IDB::ptr conn);
    static int Delete(OauthUsersInfo::ptr info, chen::IDB::ptr conn);
    static int Delete(const int64_t& id, chen::IDB::ptr conn);
    static int DeleteById( const int64_t& id, chen::IDB::ptr conn);
    static int DeleteByUsername( const std::string& username, chen::IDB::ptr conn);
    static int DeleteByEmail( const std::string& email, chen::IDB::ptr conn);
    static int QueryAll(std::vector<OauthUsersInfo::ptr>& results, chen::IDB::ptr conn);
    static OauthUsersInfo::ptr Query( const int64_t& id, chen::IDB::ptr conn);
    static OauthUsersInfo::ptr QueryByUsername( const std::string& username, chen::IDB::ptr conn);
    static OauthUsersInfo::ptr QueryByEmail( const std::string& email, chen::IDB::ptr conn);
    static int CreateTableSQLite3(chen::IDB::ptr info);
    static int CreateTableMySQL(chen::IDB::ptr info);
    static int MigrateTableSQLite3(chen::IDB::ptr info);
    static int MigrateTableMySQL(chen::IDB::ptr info);
};

} //namespace data
} //namespace auth
