/**
 * @file oauth_clients_info.cc
 * @brief OAuth 客户端注册表
 * @note Auto-generated by ORM code generator. DO NOT MODIFY.
 */
#include "oauth_clients_info.h"

#include <chen/log/log.h>

#include <map>

namespace auth {
namespace data {

static chen::Logger::ptr logger = LOG_NAME("orm");

OauthClientsInfo::OauthClientsInfo()
    :m_enabled(1)
    ,m_id()
    ,m_clientId()
    ,m_clientSecretHash()
    ,m_clientName()
    ,m_grantTypes()
    ,m_allowedScopes()
    ,m_clientUri()
    ,m_logoUri()
    ,m_redirectUris()
    ,m_createTime(time(0))
    ,m_updateTime(time(0)) {
}

std::string OauthClientsInfo::toJsonString() const {
    Json::Value v;
    v["id"] = std::to_string(m_id);
    v["client_id"] = m_clientId;
    v["client_secret_hash"] = m_clientSecretHash;
    v["client_name"] = m_clientName;
    v["redirect_uris"] = m_redirectUris;
    v["grant_types"] = m_grantTypes;
    v["allowed_scopes"] = m_allowedScopes;
    v["client_uri"] = m_clientUri;
    v["logo_uri"] = m_logoUri;
    v["enabled"] = m_enabled;
    v["create_time"] = chen::Time2Str(m_createTime);
    v["update_time"] = chen::Time2Str(m_updateTime);
    return chen::JsonUtil::ToString(v);
}

void OauthClientsInfo::setId(const int64_t& v) {
    m_id = v;
}

void OauthClientsInfo::setClientId(const std::string& v) {
    m_clientId = v;
}

void OauthClientsInfo::setClientSecretHash(const std::string& v) {
    m_clientSecretHash = v;
}

void OauthClientsInfo::setClientName(const std::string& v) {
    m_clientName = v;
}

void OauthClientsInfo::setRedirectUris(const std::string& v) {
    m_redirectUris = v;
}

void OauthClientsInfo::setGrantTypes(const std::string& v) {
    m_grantTypes = v;
}

void OauthClientsInfo::setAllowedScopes(const std::string& v) {
    m_allowedScopes = v;
}

void OauthClientsInfo::setClientUri(const std::string& v) {
    m_clientUri = v;
}

void OauthClientsInfo::setLogoUri(const std::string& v) {
    m_logoUri = v;
}

void OauthClientsInfo::setEnabled(const int32_t& v) {
    m_enabled = v;
}

void OauthClientsInfo::setCreateTime(const int64_t& v) {
    m_createTime = v;
}

void OauthClientsInfo::setUpdateTime(const int64_t& v) {
    m_updateTime = v;
}


int OauthClientsInfoDao::Update(OauthClientsInfo::ptr info, chen::IDB::ptr conn) {
    std::string sql = "update oauth_clients set client_id = ?, client_secret_hash = ?, client_name = ?, redirect_uris = ?, grant_types = ?, allowed_scopes = ?, client_uri = ?, logo_uri = ?, enabled = ?, create_time = ?, update_time = ? where id = ?";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    stmt->bindString(1, info->m_clientId);
    stmt->bindString(2, info->m_clientSecretHash);
    stmt->bindString(3, info->m_clientName);
    stmt->bindString(4, info->m_redirectUris);
    stmt->bindString(5, info->m_grantTypes);
    stmt->bindString(6, info->m_allowedScopes);
    stmt->bindString(7, info->m_clientUri);
    stmt->bindString(8, info->m_logoUri);
    stmt->bindInt32(9, info->m_enabled);
    stmt->bindTime(10, info->m_createTime);
    stmt->bindTime(11, info->m_updateTime);
    stmt->bindInt64(12, info->m_id);
    return stmt->execute();
}

int OauthClientsInfoDao::Insert(OauthClientsInfo::ptr info, chen::IDB::ptr conn) {
    std::string sql = "insert into oauth_clients (client_id, client_secret_hash, client_name, redirect_uris, grant_types, allowed_scopes, client_uri, logo_uri, enabled, create_time, update_time) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    stmt->bindString(1, info->m_clientId);
    stmt->bindString(2, info->m_clientSecretHash);
    stmt->bindString(3, info->m_clientName);
    stmt->bindString(4, info->m_redirectUris);
    stmt->bindString(5, info->m_grantTypes);
    stmt->bindString(6, info->m_allowedScopes);
    stmt->bindString(7, info->m_clientUri);
    stmt->bindString(8, info->m_logoUri);
    stmt->bindInt32(9, info->m_enabled);
    stmt->bindTime(10, info->m_createTime);
    stmt->bindTime(11, info->m_updateTime);
    int rt = stmt->execute();
    if(rt == 0) {
        info->m_id = conn->getLastInsertId();
    }
    return rt;
}

int OauthClientsInfoDao::InsertOrUpdate(OauthClientsInfo::ptr info, chen::IDB::ptr conn) {
    if(info->m_id == 0) {
        return Insert(info, conn);
    }
    std::string sql = "replace into oauth_clients (id, client_id, client_secret_hash, client_name, redirect_uris, grant_types, allowed_scopes, client_uri, logo_uri, enabled, create_time, update_time) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    stmt->bindInt64(1, info->m_id);
    stmt->bindString(2, info->m_clientId);
    stmt->bindString(3, info->m_clientSecretHash);
    stmt->bindString(4, info->m_clientName);
    stmt->bindString(5, info->m_redirectUris);
    stmt->bindString(6, info->m_grantTypes);
    stmt->bindString(7, info->m_allowedScopes);
    stmt->bindString(8, info->m_clientUri);
    stmt->bindString(9, info->m_logoUri);
    stmt->bindInt32(10, info->m_enabled);
    stmt->bindTime(11, info->m_createTime);
    stmt->bindTime(12, info->m_updateTime);
    return stmt->execute();
}

int OauthClientsInfoDao::Delete(OauthClientsInfo::ptr info, chen::IDB::ptr conn) {
    std::string sql = "delete from oauth_clients where id = ?";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    stmt->bindInt64(1, info->m_id);
    return stmt->execute();
}

int OauthClientsInfoDao::DeleteById( const int64_t& id, chen::IDB::ptr conn) {
    std::string sql = "delete from oauth_clients where id = ?";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    stmt->bindInt64(1, id);
    return stmt->execute();
}

int OauthClientsInfoDao::DeleteByClientId( const std::string& client_id, chen::IDB::ptr conn) {
    std::string sql = "delete from oauth_clients where client_id = ?";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    stmt->bindString(1, client_id);
    return stmt->execute();
}

int OauthClientsInfoDao::QueryAll(std::vector<OauthClientsInfo::ptr>& results, chen::IDB::ptr conn) {
    std::string sql = "select id, client_id, client_secret_hash, client_name, redirect_uris, grant_types, allowed_scopes, client_uri, logo_uri, enabled, create_time, update_time from oauth_clients";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    auto rt = stmt->query();
    if(!rt) {
        return stmt->getErrno();
    }
    while (rt->next()) {
        OauthClientsInfo::ptr v(new OauthClientsInfo);
        v->m_id = rt->getInt64(0);
        v->m_clientId = rt->getString(1);
        v->m_clientSecretHash = rt->getString(2);
        v->m_clientName = rt->getString(3);
        v->m_redirectUris = rt->getString(4);
        v->m_grantTypes = rt->getString(5);
        v->m_allowedScopes = rt->getString(6);
        v->m_clientUri = rt->getString(7);
        v->m_logoUri = rt->getString(8);
        v->m_enabled = rt->getInt32(9);
        v->m_createTime = rt->getTime(10);
        v->m_updateTime = rt->getTime(11);
        results.push_back(v);
    }
    return 0;
}

OauthClientsInfo::ptr OauthClientsInfoDao::Query( const int64_t& id, chen::IDB::ptr conn) {
    std::string sql = "select id, client_id, client_secret_hash, client_name, redirect_uris, grant_types, allowed_scopes, client_uri, logo_uri, enabled, create_time, update_time from oauth_clients where id = ?";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return nullptr;
    }
    stmt->bindInt64(1, id);
    auto rt = stmt->query();
    if(!rt) {
        return nullptr;
    }
    if(!rt->next()) {
        return nullptr;
    }
    OauthClientsInfo::ptr v(new OauthClientsInfo);
    v->m_id = rt->getInt64(0);
    v->m_clientId = rt->getString(1);
    v->m_clientSecretHash = rt->getString(2);
    v->m_clientName = rt->getString(3);
    v->m_redirectUris = rt->getString(4);
    v->m_grantTypes = rt->getString(5);
    v->m_allowedScopes = rt->getString(6);
    v->m_clientUri = rt->getString(7);
    v->m_logoUri = rt->getString(8);
    v->m_enabled = rt->getInt32(9);
    v->m_createTime = rt->getTime(10);
    v->m_updateTime = rt->getTime(11);
    return v;
}

OauthClientsInfo::ptr OauthClientsInfoDao::QueryByClientId( const std::string& client_id, chen::IDB::ptr conn) {
    std::string sql = "select id, client_id, client_secret_hash, client_name, redirect_uris, grant_types, allowed_scopes, client_uri, logo_uri, enabled, create_time, update_time from oauth_clients where client_id = ?";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return nullptr;
    }
    stmt->bindString(1, client_id);
    auto rt = stmt->query();
    if(!rt) {
        return nullptr;
    }
    if(!rt->next()) {
        return nullptr;
    }
    OauthClientsInfo::ptr v(new OauthClientsInfo);
    v->m_id = rt->getInt64(0);
    v->m_clientId = rt->getString(1);
    v->m_clientSecretHash = rt->getString(2);
    v->m_clientName = rt->getString(3);
    v->m_redirectUris = rt->getString(4);
    v->m_grantTypes = rt->getString(5);
    v->m_allowedScopes = rt->getString(6);
    v->m_clientUri = rt->getString(7);
    v->m_logoUri = rt->getString(8);
    v->m_enabled = rt->getInt32(9);
    v->m_createTime = rt->getTime(10);
    v->m_updateTime = rt->getTime(11);
    return v;
}

int OauthClientsInfoDao::CreateTableSQLite3(chen::IDB::ptr conn) {
    return conn->execute("CREATE TABLE IF NOT EXISTS oauth_clients("
            "id INTEGER PRIMARY KEY AUTOINCREMENT,"
            "client_id TEXT NOT NULL DEFAULT '',"
            "client_secret_hash TEXT NOT NULL DEFAULT '',"
            "client_name TEXT NOT NULL DEFAULT '',"
            "redirect_uris TEXT NOT NULL DEFAULT '',"
            "grant_types TEXT NOT NULL DEFAULT '',"
            "allowed_scopes TEXT NOT NULL DEFAULT '',"
            "client_uri TEXT NOT NULL DEFAULT '',"
            "logo_uri TEXT NOT NULL DEFAULT '',"
            "enabled INTEGER NOT NULL DEFAULT 1,"
            "create_time TIMESTAMP NOT NULL DEFAULT current_timestamp,"
            "update_time TIMESTAMP NOT NULL DEFAULT current_timestamp);"
            "CREATE UNIQUE INDEX IF NOT EXISTS oauth_clients_client_id ON oauth_clients(client_id);"
            );
}

int OauthClientsInfoDao::CreateTableMySQL(chen::IDB::ptr conn) {
    return conn->execute("CREATE TABLE IF NOT EXISTS oauth_clients("
            "`id` bigint AUTO_INCREMENT COMMENT '主键',"
            "`client_id` varchar(128) NOT NULL DEFAULT '' COMMENT '客户端 ID',"
            "`client_secret_hash` varchar(128) NOT NULL DEFAULT '' COMMENT 'client_secret 的 bcrypt 哈希',"
            "`client_name` varchar(128) NOT NULL DEFAULT '' COMMENT '客户端名称',"
            "`redirect_uris` text NOT NULL COMMENT '回调 URI 白名单（JSON 数组）',"
            "`grant_types` varchar(128) NOT NULL DEFAULT '' COMMENT '允许的 grant_type',"
            "`allowed_scopes` varchar(128) NOT NULL DEFAULT '' COMMENT '允许的 scope 列表',"
            "`client_uri` varchar(128) NOT NULL DEFAULT '' COMMENT '客户端主页',"
            "`logo_uri` varchar(128) NOT NULL DEFAULT '' COMMENT '客户端图标',"
            "`enabled` int NOT NULL DEFAULT 1 COMMENT '是否启用',"
            "`create_time` timestamp NOT NULL DEFAULT current_timestamp COMMENT '创建时间',"
            "`update_time` timestamp NOT NULL DEFAULT current_timestamp COMMENT '更新时间',"
            "PRIMARY KEY(`id`),"
            "UNIQUE KEY `oauth_clients_client_id` (`client_id`)) COMMENT='OAuth 客户端注册表'");
}

int OauthClientsInfoDao::MigrateTableSQLite3(chen::IDB::ptr conn) {
    auto data = conn->query("PRAGMA table_info(oauth_clients)");
    if (!data) {
        ERROR(logger) << "PRAGMA table_info(oauth_clients) errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    std::map<std::string, std::string> existing_cols;  // name -> type
    while (data->next()) {
        existing_cols[data->getString(1)] = data->getString(2);
    }

    bool need_recreate = false;
    {
        auto it = existing_cols.find("id");
        if (it != existing_cols.end() && it->second != "INTEGER") {
            INFO(logger) << "Column type changed: oauth_clients.id " << it->second << " -> INTEGER";
            need_recreate = true;
        }
    }
    {
        auto it = existing_cols.find("client_id");
        if (it != existing_cols.end() && it->second != "TEXT") {
            INFO(logger) << "Column type changed: oauth_clients.client_id " << it->second << " -> TEXT";
            need_recreate = true;
        }
    }
    {
        auto it = existing_cols.find("client_secret_hash");
        if (it != existing_cols.end() && it->second != "TEXT") {
            INFO(logger) << "Column type changed: oauth_clients.client_secret_hash " << it->second << " -> TEXT";
            need_recreate = true;
        }
    }
    {
        auto it = existing_cols.find("client_name");
        if (it != existing_cols.end() && it->second != "TEXT") {
            INFO(logger) << "Column type changed: oauth_clients.client_name " << it->second << " -> TEXT";
            need_recreate = true;
        }
    }
    {
        auto it = existing_cols.find("redirect_uris");
        if (it != existing_cols.end() && it->second != "TEXT") {
            INFO(logger) << "Column type changed: oauth_clients.redirect_uris " << it->second << " -> TEXT";
            need_recreate = true;
        }
    }
    {
        auto it = existing_cols.find("grant_types");
        if (it != existing_cols.end() && it->second != "TEXT") {
            INFO(logger) << "Column type changed: oauth_clients.grant_types " << it->second << " -> TEXT";
            need_recreate = true;
        }
    }
    {
        auto it = existing_cols.find("allowed_scopes");
        if (it != existing_cols.end() && it->second != "TEXT") {
            INFO(logger) << "Column type changed: oauth_clients.allowed_scopes " << it->second << " -> TEXT";
            need_recreate = true;
        }
    }
    {
        auto it = existing_cols.find("client_uri");
        if (it != existing_cols.end() && it->second != "TEXT") {
            INFO(logger) << "Column type changed: oauth_clients.client_uri " << it->second << " -> TEXT";
            need_recreate = true;
        }
    }
    {
        auto it = existing_cols.find("logo_uri");
        if (it != existing_cols.end() && it->second != "TEXT") {
            INFO(logger) << "Column type changed: oauth_clients.logo_uri " << it->second << " -> TEXT";
            need_recreate = true;
        }
    }
    {
        auto it = existing_cols.find("enabled");
        if (it != existing_cols.end() && it->second != "INTEGER") {
            INFO(logger) << "Column type changed: oauth_clients.enabled " << it->second << " -> INTEGER";
            need_recreate = true;
        }
    }
    {
        auto it = existing_cols.find("create_time");
        if (it != existing_cols.end() && it->second != "TIMESTAMP") {
            INFO(logger) << "Column type changed: oauth_clients.create_time " << it->second << " -> TIMESTAMP";
            need_recreate = true;
        }
    }
    {
        auto it = existing_cols.find("update_time");
        if (it != existing_cols.end() && it->second != "TIMESTAMP") {
            INFO(logger) << "Column type changed: oauth_clients.update_time " << it->second << " -> TIMESTAMP";
            need_recreate = true;
        }
    }
    if (!need_recreate) {
        for (auto& [name, _] : existing_cols) {
            (void)_;  // suppress unused warning
            bool found = false;
            if (name == "id") found = true;
            if (name == "client_id") found = true;
            if (name == "client_secret_hash") found = true;
            if (name == "client_name") found = true;
            if (name == "redirect_uris") found = true;
            if (name == "grant_types") found = true;
            if (name == "allowed_scopes") found = true;
            if (name == "client_uri") found = true;
            if (name == "logo_uri") found = true;
            if (name == "enabled") found = true;
            if (name == "create_time") found = true;
            if (name == "update_time") found = true;
            if (!found) {
                need_recreate = true;
                WARN(logger) << "Column oauth_clients." << name << " removed, table recreate required";
                break;
            }
        }
    }

    if (need_recreate) {
        INFO(logger) << "Recreating table oauth_clients";

        std::vector<std::string> common_cols;
        if (existing_cols.find("id") != existing_cols.end()) {
            common_cols.push_back("id");
        }
        if (existing_cols.find("client_id") != existing_cols.end()) {
            common_cols.push_back("client_id");
        }
        if (existing_cols.find("client_secret_hash") != existing_cols.end()) {
            common_cols.push_back("client_secret_hash");
        }
        if (existing_cols.find("client_name") != existing_cols.end()) {
            common_cols.push_back("client_name");
        }
        if (existing_cols.find("redirect_uris") != existing_cols.end()) {
            common_cols.push_back("redirect_uris");
        }
        if (existing_cols.find("grant_types") != existing_cols.end()) {
            common_cols.push_back("grant_types");
        }
        if (existing_cols.find("allowed_scopes") != existing_cols.end()) {
            common_cols.push_back("allowed_scopes");
        }
        if (existing_cols.find("client_uri") != existing_cols.end()) {
            common_cols.push_back("client_uri");
        }
        if (existing_cols.find("logo_uri") != existing_cols.end()) {
            common_cols.push_back("logo_uri");
        }
        if (existing_cols.find("enabled") != existing_cols.end()) {
            common_cols.push_back("enabled");
        }
        if (existing_cols.find("create_time") != existing_cols.end()) {
            common_cols.push_back("create_time");
        }
        if (existing_cols.find("update_time") != existing_cols.end()) {
            common_cols.push_back("update_time");
        }

        if (conn->execute("ALTER TABLE oauth_clients RENAME TO oauth_clients_tmp")) {
            ERROR(logger) << "RENAME TABLE oauth_clients failed";
            return conn->getErrno();
        }
        CreateTableSQLite3(conn);
        if (!common_cols.empty()) {
            std::string cols;
            for (size_t i = 0; i < common_cols.size(); ++i) {
                if (i) cols += ",";
                cols += common_cols[i];
            }
            std::string sql = "INSERT INTO oauth_clients (" + cols + ") SELECT " + cols + " FROM oauth_clients_tmp";
            if (int rt = conn->execute(sql)) {
                ERROR(logger) << "copy data from oauth_clients_tmp to oauth_clients failed, errno=" << rt;
                // don't return; try to continue
            }
        }
        conn->execute("DROP TABLE oauth_clients_tmp");
        return 0;
    }

    if (existing_cols.find("client_id") == existing_cols.end()) {
        INFO(logger) << "Adding column oauth_clients.client_id";
        int rt = conn->execute("ALTER TABLE oauth_clients ADD COLUMN client_id TEXT NOT NULL DEFAULT ''");
        if (rt) {
            ERROR(logger) << "ALTER TABLE oauth_clients ADD COLUMN client_id failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("client_secret_hash") == existing_cols.end()) {
        INFO(logger) << "Adding column oauth_clients.client_secret_hash";
        int rt = conn->execute("ALTER TABLE oauth_clients ADD COLUMN client_secret_hash TEXT NOT NULL DEFAULT ''");
        if (rt) {
            ERROR(logger) << "ALTER TABLE oauth_clients ADD COLUMN client_secret_hash failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("client_name") == existing_cols.end()) {
        INFO(logger) << "Adding column oauth_clients.client_name";
        int rt = conn->execute("ALTER TABLE oauth_clients ADD COLUMN client_name TEXT NOT NULL DEFAULT ''");
        if (rt) {
            ERROR(logger) << "ALTER TABLE oauth_clients ADD COLUMN client_name failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("redirect_uris") == existing_cols.end()) {
        INFO(logger) << "Adding column oauth_clients.redirect_uris";
        int rt = conn->execute("ALTER TABLE oauth_clients ADD COLUMN redirect_uris TEXT NOT NULL DEFAULT ''");
        if (rt) {
            ERROR(logger) << "ALTER TABLE oauth_clients ADD COLUMN redirect_uris failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("grant_types") == existing_cols.end()) {
        INFO(logger) << "Adding column oauth_clients.grant_types";
        int rt = conn->execute("ALTER TABLE oauth_clients ADD COLUMN grant_types TEXT NOT NULL DEFAULT ''");
        if (rt) {
            ERROR(logger) << "ALTER TABLE oauth_clients ADD COLUMN grant_types failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("allowed_scopes") == existing_cols.end()) {
        INFO(logger) << "Adding column oauth_clients.allowed_scopes";
        int rt = conn->execute("ALTER TABLE oauth_clients ADD COLUMN allowed_scopes TEXT NOT NULL DEFAULT ''");
        if (rt) {
            ERROR(logger) << "ALTER TABLE oauth_clients ADD COLUMN allowed_scopes failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("client_uri") == existing_cols.end()) {
        INFO(logger) << "Adding column oauth_clients.client_uri";
        int rt = conn->execute("ALTER TABLE oauth_clients ADD COLUMN client_uri TEXT NOT NULL DEFAULT ''");
        if (rt) {
            ERROR(logger) << "ALTER TABLE oauth_clients ADD COLUMN client_uri failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("logo_uri") == existing_cols.end()) {
        INFO(logger) << "Adding column oauth_clients.logo_uri";
        int rt = conn->execute("ALTER TABLE oauth_clients ADD COLUMN logo_uri TEXT NOT NULL DEFAULT ''");
        if (rt) {
            ERROR(logger) << "ALTER TABLE oauth_clients ADD COLUMN logo_uri failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("enabled") == existing_cols.end()) {
        INFO(logger) << "Adding column oauth_clients.enabled";
        int rt = conn->execute("ALTER TABLE oauth_clients ADD COLUMN enabled INTEGER NOT NULL DEFAULT 1");
        if (rt) {
            ERROR(logger) << "ALTER TABLE oauth_clients ADD COLUMN enabled failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("create_time") == existing_cols.end()) {
        INFO(logger) << "Adding column oauth_clients.create_time";
        int rt = conn->execute("ALTER TABLE oauth_clients ADD COLUMN create_time TIMESTAMP NOT NULL DEFAULT current_timestamp");
        if (rt) {
            ERROR(logger) << "ALTER TABLE oauth_clients ADD COLUMN create_time failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("update_time") == existing_cols.end()) {
        INFO(logger) << "Adding column oauth_clients.update_time";
        int rt = conn->execute("ALTER TABLE oauth_clients ADD COLUMN update_time TIMESTAMP NOT NULL DEFAULT current_timestamp");
        if (rt) {
            ERROR(logger) << "ALTER TABLE oauth_clients ADD COLUMN update_time failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    return 0;
}

int OauthClientsInfoDao::MigrateTableMySQL(chen::IDB::ptr conn) {
    auto data = conn->query("SHOW COLUMNS FROM oauth_clients");
    if (!data) {
        ERROR(logger) << "SHOW COLUMNS FROM oauth_clients errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    std::map<std::string, std::string> existing_cols;  // name -> type
    while (data->next()) {
        existing_cols[data->getString(0)] = data->getString(1);
    }

    {
        auto it = existing_cols.find("id");
        if (it != existing_cols.end() && it->second != "bigint") {
            INFO(logger) << "Modifying column oauth_clients.id " << it->second << " -> bigint";
            int rt = conn->execute("ALTER TABLE oauth_clients MODIFY COLUMN `id` bigint NOT NULL DEFAULT 0 COMMENT '主键'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN oauth_clients.id failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }
    {
        auto it = existing_cols.find("client_id");
        if (it != existing_cols.end() && it->second != "varchar(128)") {
            INFO(logger) << "Modifying column oauth_clients.client_id " << it->second << " -> varchar(128)";
            int rt = conn->execute("ALTER TABLE oauth_clients MODIFY COLUMN `client_id` varchar(128) NOT NULL DEFAULT '' COMMENT '客户端 ID'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN oauth_clients.client_id failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }
    {
        auto it = existing_cols.find("client_secret_hash");
        if (it != existing_cols.end() && it->second != "varchar(128)") {
            INFO(logger) << "Modifying column oauth_clients.client_secret_hash " << it->second << " -> varchar(128)";
            int rt = conn->execute("ALTER TABLE oauth_clients MODIFY COLUMN `client_secret_hash` varchar(128) NOT NULL DEFAULT '' COMMENT 'client_secret 的 bcrypt 哈希'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN oauth_clients.client_secret_hash failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }
    {
        auto it = existing_cols.find("client_name");
        if (it != existing_cols.end() && it->second != "varchar(128)") {
            INFO(logger) << "Modifying column oauth_clients.client_name " << it->second << " -> varchar(128)";
            int rt = conn->execute("ALTER TABLE oauth_clients MODIFY COLUMN `client_name` varchar(128) NOT NULL DEFAULT '' COMMENT '客户端名称'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN oauth_clients.client_name failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }
    {
        auto it = existing_cols.find("redirect_uris");
        if (it != existing_cols.end() && it->second != "text") {
            INFO(logger) << "Modifying column oauth_clients.redirect_uris " << it->second << " -> text";
            int rt = conn->execute("ALTER TABLE oauth_clients MODIFY COLUMN `redirect_uris` text NOT NULL COMMENT '回调 URI 白名单（JSON 数组）'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN oauth_clients.redirect_uris failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }
    {
        auto it = existing_cols.find("grant_types");
        if (it != existing_cols.end() && it->second != "varchar(128)") {
            INFO(logger) << "Modifying column oauth_clients.grant_types " << it->second << " -> varchar(128)";
            int rt = conn->execute("ALTER TABLE oauth_clients MODIFY COLUMN `grant_types` varchar(128) NOT NULL DEFAULT '' COMMENT '允许的 grant_type'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN oauth_clients.grant_types failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }
    {
        auto it = existing_cols.find("allowed_scopes");
        if (it != existing_cols.end() && it->second != "varchar(128)") {
            INFO(logger) << "Modifying column oauth_clients.allowed_scopes " << it->second << " -> varchar(128)";
            int rt = conn->execute("ALTER TABLE oauth_clients MODIFY COLUMN `allowed_scopes` varchar(128) NOT NULL DEFAULT '' COMMENT '允许的 scope 列表'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN oauth_clients.allowed_scopes failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }
    {
        auto it = existing_cols.find("client_uri");
        if (it != existing_cols.end() && it->second != "varchar(128)") {
            INFO(logger) << "Modifying column oauth_clients.client_uri " << it->second << " -> varchar(128)";
            int rt = conn->execute("ALTER TABLE oauth_clients MODIFY COLUMN `client_uri` varchar(128) NOT NULL DEFAULT '' COMMENT '客户端主页'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN oauth_clients.client_uri failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }
    {
        auto it = existing_cols.find("logo_uri");
        if (it != existing_cols.end() && it->second != "varchar(128)") {
            INFO(logger) << "Modifying column oauth_clients.logo_uri " << it->second << " -> varchar(128)";
            int rt = conn->execute("ALTER TABLE oauth_clients MODIFY COLUMN `logo_uri` varchar(128) NOT NULL DEFAULT '' COMMENT '客户端图标'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN oauth_clients.logo_uri failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }
    {
        auto it = existing_cols.find("enabled");
        if (it != existing_cols.end() && it->second != "int") {
            INFO(logger) << "Modifying column oauth_clients.enabled " << it->second << " -> int";
            int rt = conn->execute("ALTER TABLE oauth_clients MODIFY COLUMN `enabled` int NOT NULL DEFAULT 1 COMMENT '是否启用'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN oauth_clients.enabled failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }
    {
        auto it = existing_cols.find("create_time");
        if (it != existing_cols.end() && it->second != "timestamp") {
            INFO(logger) << "Modifying column oauth_clients.create_time " << it->second << " -> timestamp";
            int rt = conn->execute("ALTER TABLE oauth_clients MODIFY COLUMN `create_time` timestamp NOT NULL DEFAULT current_timestamp COMMENT '创建时间'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN oauth_clients.create_time failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }
    {
        auto it = existing_cols.find("update_time");
        if (it != existing_cols.end() && it->second != "timestamp") {
            INFO(logger) << "Modifying column oauth_clients.update_time " << it->second << " -> timestamp";
            int rt = conn->execute("ALTER TABLE oauth_clients MODIFY COLUMN `update_time` timestamp NOT NULL DEFAULT current_timestamp COMMENT '更新时间'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN oauth_clients.update_time failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }

    for (auto& [name, _] : existing_cols) {
        (void)_;
        bool found = false;
        if (name == "id") found = true;
        if (name == "client_id") found = true;
        if (name == "client_secret_hash") found = true;
        if (name == "client_name") found = true;
        if (name == "redirect_uris") found = true;
        if (name == "grant_types") found = true;
        if (name == "allowed_scopes") found = true;
        if (name == "client_uri") found = true;
        if (name == "logo_uri") found = true;
        if (name == "enabled") found = true;
        if (name == "create_time") found = true;
        if (name == "update_time") found = true;
        if (!found) {
            WARN(logger) << "Dropping column oauth_clients." << name << " (not in schema, data will be lost)";
            int rt = conn->execute("ALTER TABLE oauth_clients DROP COLUMN `" + name + "`");
            if (rt) {
                ERROR(logger) << "DROP COLUMN oauth_clients." << name << " failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }

    if (existing_cols.find("client_id") == existing_cols.end()) {
        INFO(logger) << "Adding column oauth_clients.client_id";
        int rt = conn->execute("ALTER TABLE oauth_clients ADD COLUMN `client_id` varchar(128) NOT NULL DEFAULT '' COMMENT '客户端 ID'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE oauth_clients ADD COLUMN client_id failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("client_secret_hash") == existing_cols.end()) {
        INFO(logger) << "Adding column oauth_clients.client_secret_hash";
        int rt = conn->execute("ALTER TABLE oauth_clients ADD COLUMN `client_secret_hash` varchar(128) NOT NULL DEFAULT '' COMMENT 'client_secret 的 bcrypt 哈希'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE oauth_clients ADD COLUMN client_secret_hash failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("client_name") == existing_cols.end()) {
        INFO(logger) << "Adding column oauth_clients.client_name";
        int rt = conn->execute("ALTER TABLE oauth_clients ADD COLUMN `client_name` varchar(128) NOT NULL DEFAULT '' COMMENT '客户端名称'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE oauth_clients ADD COLUMN client_name failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("redirect_uris") == existing_cols.end()) {
        INFO(logger) << "Adding column oauth_clients.redirect_uris";
        int rt = conn->execute("ALTER TABLE oauth_clients ADD COLUMN `redirect_uris` text COMMENT '回调 URI 白名单（JSON 数组）'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE oauth_clients ADD COLUMN redirect_uris failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("grant_types") == existing_cols.end()) {
        INFO(logger) << "Adding column oauth_clients.grant_types";
        int rt = conn->execute("ALTER TABLE oauth_clients ADD COLUMN `grant_types` varchar(128) NOT NULL DEFAULT '' COMMENT '允许的 grant_type'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE oauth_clients ADD COLUMN grant_types failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("allowed_scopes") == existing_cols.end()) {
        INFO(logger) << "Adding column oauth_clients.allowed_scopes";
        int rt = conn->execute("ALTER TABLE oauth_clients ADD COLUMN `allowed_scopes` varchar(128) NOT NULL DEFAULT '' COMMENT '允许的 scope 列表'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE oauth_clients ADD COLUMN allowed_scopes failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("client_uri") == existing_cols.end()) {
        INFO(logger) << "Adding column oauth_clients.client_uri";
        int rt = conn->execute("ALTER TABLE oauth_clients ADD COLUMN `client_uri` varchar(128) NOT NULL DEFAULT '' COMMENT '客户端主页'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE oauth_clients ADD COLUMN client_uri failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("logo_uri") == existing_cols.end()) {
        INFO(logger) << "Adding column oauth_clients.logo_uri";
        int rt = conn->execute("ALTER TABLE oauth_clients ADD COLUMN `logo_uri` varchar(128) NOT NULL DEFAULT '' COMMENT '客户端图标'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE oauth_clients ADD COLUMN logo_uri failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("enabled") == existing_cols.end()) {
        INFO(logger) << "Adding column oauth_clients.enabled";
        int rt = conn->execute("ALTER TABLE oauth_clients ADD COLUMN `enabled` int NOT NULL DEFAULT 1 COMMENT '是否启用'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE oauth_clients ADD COLUMN enabled failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("create_time") == existing_cols.end()) {
        INFO(logger) << "Adding column oauth_clients.create_time";
        int rt = conn->execute("ALTER TABLE oauth_clients ADD COLUMN `create_time` timestamp NOT NULL DEFAULT current_timestamp COMMENT '创建时间'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE oauth_clients ADD COLUMN create_time failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("update_time") == existing_cols.end()) {
        INFO(logger) << "Adding column oauth_clients.update_time";
        int rt = conn->execute("ALTER TABLE oauth_clients ADD COLUMN `update_time` timestamp NOT NULL DEFAULT current_timestamp COMMENT '更新时间'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE oauth_clients ADD COLUMN update_time failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    return 0;
}


} //namespace data
} //namespace auth
