/**
 * @file oauth_users_info.cc
 * @brief OIDC 用户表
 * @note Auto-generated by ORM code generator. DO NOT MODIFY.
 */
#include "oauth_users_info.h"

#include <chen/log/log.h>

#include <map>

namespace auth {
namespace data {

static chen::Logger::ptr logger = LOG_NAME("orm");

OauthUsersInfo::OauthUsersInfo()
    :m_emailVerified(0)
    ,m_enabled(1)
    ,m_id()
    ,m_username()
    ,m_email()
    ,m_passwordHash()
    ,m_displayName()
    ,m_avatarUrl()
    ,m_createTime(time(0))
    ,m_updateTime(time(0)) {
}

std::string OauthUsersInfo::toJsonString() const {
    Json::Value v;
    v["id"] = std::to_string(m_id);
    v["username"] = m_username;
    v["email"] = m_email;
    v["password_hash"] = m_passwordHash;
    v["display_name"] = m_displayName;
    v["avatar_url"] = m_avatarUrl;
    v["email_verified"] = m_emailVerified;
    v["enabled"] = m_enabled;
    v["create_time"] = chen::Time2Str(m_createTime);
    v["update_time"] = chen::Time2Str(m_updateTime);
    return chen::JsonUtil::ToString(v);
}

void OauthUsersInfo::setId(const int64_t& v) {
    m_id = v;
}

void OauthUsersInfo::setUsername(const std::string& v) {
    m_username = v;
}

void OauthUsersInfo::setEmail(const std::string& v) {
    m_email = v;
}

void OauthUsersInfo::setPasswordHash(const std::string& v) {
    m_passwordHash = v;
}

void OauthUsersInfo::setDisplayName(const std::string& v) {
    m_displayName = v;
}

void OauthUsersInfo::setAvatarUrl(const std::string& v) {
    m_avatarUrl = v;
}

void OauthUsersInfo::setEmailVerified(const int32_t& v) {
    m_emailVerified = v;
}

void OauthUsersInfo::setEnabled(const int32_t& v) {
    m_enabled = v;
}

void OauthUsersInfo::setCreateTime(const int64_t& v) {
    m_createTime = v;
}

void OauthUsersInfo::setUpdateTime(const int64_t& v) {
    m_updateTime = v;
}


int OauthUsersInfoDao::Update(OauthUsersInfo::ptr info, chen::IDB::ptr conn) {
    std::string sql = "update oauth_users set username = ?, email = ?, password_hash = ?, display_name = ?, avatar_url = ?, email_verified = ?, enabled = ?, create_time = ?, update_time = ? where id = ?";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    stmt->bindString(1, info->m_username);
    stmt->bindString(2, info->m_email);
    stmt->bindString(3, info->m_passwordHash);
    stmt->bindString(4, info->m_displayName);
    stmt->bindString(5, info->m_avatarUrl);
    stmt->bindInt32(6, info->m_emailVerified);
    stmt->bindInt32(7, info->m_enabled);
    stmt->bindTime(8, info->m_createTime);
    stmt->bindTime(9, info->m_updateTime);
    stmt->bindInt64(10, info->m_id);
    return stmt->execute();
}

int OauthUsersInfoDao::Insert(OauthUsersInfo::ptr info, chen::IDB::ptr conn) {
    std::string sql = "insert into oauth_users (username, email, password_hash, display_name, avatar_url, email_verified, enabled, create_time, update_time) values (?, ?, ?, ?, ?, ?, ?, ?, ?)";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    stmt->bindString(1, info->m_username);
    stmt->bindString(2, info->m_email);
    stmt->bindString(3, info->m_passwordHash);
    stmt->bindString(4, info->m_displayName);
    stmt->bindString(5, info->m_avatarUrl);
    stmt->bindInt32(6, info->m_emailVerified);
    stmt->bindInt32(7, info->m_enabled);
    stmt->bindTime(8, info->m_createTime);
    stmt->bindTime(9, info->m_updateTime);
    int rt = stmt->execute();
    if(rt == 0) {
        info->m_id = conn->getLastInsertId();
    }
    return rt;
}

int OauthUsersInfoDao::InsertOrUpdate(OauthUsersInfo::ptr info, chen::IDB::ptr conn) {
    if(info->m_id == 0) {
        return Insert(info, conn);
    }
    std::string sql = "replace into oauth_users (id, username, email, password_hash, display_name, avatar_url, email_verified, enabled, create_time, update_time) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    stmt->bindInt64(1, info->m_id);
    stmt->bindString(2, info->m_username);
    stmt->bindString(3, info->m_email);
    stmt->bindString(4, info->m_passwordHash);
    stmt->bindString(5, info->m_displayName);
    stmt->bindString(6, info->m_avatarUrl);
    stmt->bindInt32(7, info->m_emailVerified);
    stmt->bindInt32(8, info->m_enabled);
    stmt->bindTime(9, info->m_createTime);
    stmt->bindTime(10, info->m_updateTime);
    return stmt->execute();
}

int OauthUsersInfoDao::Delete(OauthUsersInfo::ptr info, chen::IDB::ptr conn) {
    std::string sql = "delete from oauth_users where id = ?";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    stmt->bindInt64(1, info->m_id);
    return stmt->execute();
}

int OauthUsersInfoDao::DeleteById( const int64_t& id, chen::IDB::ptr conn) {
    std::string sql = "delete from oauth_users where id = ?";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    stmt->bindInt64(1, id);
    return stmt->execute();
}

int OauthUsersInfoDao::DeleteByUsername( const std::string& username, chen::IDB::ptr conn) {
    std::string sql = "delete from oauth_users where username = ?";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    stmt->bindString(1, username);
    return stmt->execute();
}

int OauthUsersInfoDao::DeleteByEmail( const std::string& email, chen::IDB::ptr conn) {
    std::string sql = "delete from oauth_users where email = ?";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    stmt->bindString(1, email);
    return stmt->execute();
}

int OauthUsersInfoDao::QueryAll(std::vector<OauthUsersInfo::ptr>& results, chen::IDB::ptr conn) {
    std::string sql = "select id, username, email, password_hash, display_name, avatar_url, email_verified, enabled, create_time, update_time from oauth_users";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    auto rt = stmt->query();
    if(!rt) {
        return stmt->getErrno();
    }
    while (rt->next()) {
        OauthUsersInfo::ptr v(new OauthUsersInfo);
        v->m_id = rt->getInt64(0);
        v->m_username = rt->getString(1);
        v->m_email = rt->getString(2);
        v->m_passwordHash = rt->getString(3);
        v->m_displayName = rt->getString(4);
        v->m_avatarUrl = rt->getString(5);
        v->m_emailVerified = rt->getInt32(6);
        v->m_enabled = rt->getInt32(7);
        v->m_createTime = rt->getTime(8);
        v->m_updateTime = rt->getTime(9);
        results.push_back(v);
    }
    return 0;
}

OauthUsersInfo::ptr OauthUsersInfoDao::Query( const int64_t& id, chen::IDB::ptr conn) {
    std::string sql = "select id, username, email, password_hash, display_name, avatar_url, email_verified, enabled, create_time, update_time from oauth_users where id = ?";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return nullptr;
    }
    stmt->bindInt64(1, id);
    auto rt = stmt->query();
    if(!rt) {
        return nullptr;
    }
    if(!rt->next()) {
        return nullptr;
    }
    OauthUsersInfo::ptr v(new OauthUsersInfo);
    v->m_id = rt->getInt64(0);
    v->m_username = rt->getString(1);
    v->m_email = rt->getString(2);
    v->m_passwordHash = rt->getString(3);
    v->m_displayName = rt->getString(4);
    v->m_avatarUrl = rt->getString(5);
    v->m_emailVerified = rt->getInt32(6);
    v->m_enabled = rt->getInt32(7);
    v->m_createTime = rt->getTime(8);
    v->m_updateTime = rt->getTime(9);
    return v;
}

OauthUsersInfo::ptr OauthUsersInfoDao::QueryByUsername( const std::string& username, chen::IDB::ptr conn) {
    std::string sql = "select id, username, email, password_hash, display_name, avatar_url, email_verified, enabled, create_time, update_time from oauth_users where username = ?";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return nullptr;
    }
    stmt->bindString(1, username);
    auto rt = stmt->query();
    if(!rt) {
        return nullptr;
    }
    if(!rt->next()) {
        return nullptr;
    }
    OauthUsersInfo::ptr v(new OauthUsersInfo);
    v->m_id = rt->getInt64(0);
    v->m_username = rt->getString(1);
    v->m_email = rt->getString(2);
    v->m_passwordHash = rt->getString(3);
    v->m_displayName = rt->getString(4);
    v->m_avatarUrl = rt->getString(5);
    v->m_emailVerified = rt->getInt32(6);
    v->m_enabled = rt->getInt32(7);
    v->m_createTime = rt->getTime(8);
    v->m_updateTime = rt->getTime(9);
    return v;
}

OauthUsersInfo::ptr OauthUsersInfoDao::QueryByEmail( const std::string& email, chen::IDB::ptr conn) {
    std::string sql = "select id, username, email, password_hash, display_name, avatar_url, email_verified, enabled, create_time, update_time from oauth_users where email = ?";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return nullptr;
    }
    stmt->bindString(1, email);
    auto rt = stmt->query();
    if(!rt) {
        return nullptr;
    }
    if(!rt->next()) {
        return nullptr;
    }
    OauthUsersInfo::ptr v(new OauthUsersInfo);
    v->m_id = rt->getInt64(0);
    v->m_username = rt->getString(1);
    v->m_email = rt->getString(2);
    v->m_passwordHash = rt->getString(3);
    v->m_displayName = rt->getString(4);
    v->m_avatarUrl = rt->getString(5);
    v->m_emailVerified = rt->getInt32(6);
    v->m_enabled = rt->getInt32(7);
    v->m_createTime = rt->getTime(8);
    v->m_updateTime = rt->getTime(9);
    return v;
}

int OauthUsersInfoDao::CreateTableSQLite3(chen::IDB::ptr conn) {
    return conn->execute("CREATE TABLE IF NOT EXISTS oauth_users("
            "id INTEGER PRIMARY KEY AUTOINCREMENT,"
            "username TEXT NOT NULL DEFAULT '',"
            "email TEXT NOT NULL DEFAULT '',"
            "password_hash TEXT NOT NULL DEFAULT '',"
            "display_name TEXT NOT NULL DEFAULT '',"
            "avatar_url TEXT NOT NULL DEFAULT '',"
            "email_verified INTEGER NOT NULL DEFAULT 0,"
            "enabled INTEGER NOT NULL DEFAULT 1,"
            "create_time TIMESTAMP NOT NULL DEFAULT current_timestamp,"
            "update_time TIMESTAMP NOT NULL DEFAULT current_timestamp);"
            "CREATE UNIQUE INDEX IF NOT EXISTS oauth_users_username ON oauth_users(username);"
            "CREATE UNIQUE INDEX IF NOT EXISTS oauth_users_email ON oauth_users(email);"
            );
}

int OauthUsersInfoDao::CreateTableMySQL(chen::IDB::ptr conn) {
    return conn->execute("CREATE TABLE IF NOT EXISTS oauth_users("
            "`id` bigint AUTO_INCREMENT COMMENT '主键',"
            "`username` varchar(128) NOT NULL DEFAULT '' COMMENT '用户名',"
            "`email` varchar(128) NOT NULL DEFAULT '' COMMENT '邮箱',"
            "`password_hash` varchar(128) NOT NULL DEFAULT '' COMMENT 'bcrypt 密码哈希',"
            "`display_name` varchar(128) NOT NULL DEFAULT '' COMMENT '显示名称',"
            "`avatar_url` varchar(128) NOT NULL DEFAULT '' COMMENT '头像 URL',"
            "`email_verified` int NOT NULL DEFAULT 0 COMMENT '邮箱是否已验证',"
            "`enabled` int NOT NULL DEFAULT 1 COMMENT '是否启用',"
            "`create_time` timestamp NOT NULL DEFAULT current_timestamp COMMENT '创建时间',"
            "`update_time` timestamp NOT NULL DEFAULT current_timestamp COMMENT '更新时间',"
            "PRIMARY KEY(`id`),"
            "UNIQUE KEY `oauth_users_username` (`username`),"
            "UNIQUE KEY `oauth_users_email` (`email`)) COMMENT='OIDC 用户表'");
}

int OauthUsersInfoDao::MigrateTableSQLite3(chen::IDB::ptr conn) {
    auto data = conn->query("PRAGMA table_info(oauth_users)");
    if (!data) {
        ERROR(logger) << "PRAGMA table_info(oauth_users) errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    std::map<std::string, std::string> existing_cols;  // name -> type
    while (data->next()) {
        existing_cols[data->getString(1)] = data->getString(2);
    }

    bool need_recreate = false;
    {
        auto it = existing_cols.find("id");
        if (it != existing_cols.end() && it->second != "INTEGER") {
            INFO(logger) << "Column type changed: oauth_users.id " << it->second << " -> INTEGER";
            need_recreate = true;
        }
    }
    {
        auto it = existing_cols.find("username");
        if (it != existing_cols.end() && it->second != "TEXT") {
            INFO(logger) << "Column type changed: oauth_users.username " << it->second << " -> TEXT";
            need_recreate = true;
        }
    }
    {
        auto it = existing_cols.find("email");
        if (it != existing_cols.end() && it->second != "TEXT") {
            INFO(logger) << "Column type changed: oauth_users.email " << it->second << " -> TEXT";
            need_recreate = true;
        }
    }
    {
        auto it = existing_cols.find("password_hash");
        if (it != existing_cols.end() && it->second != "TEXT") {
            INFO(logger) << "Column type changed: oauth_users.password_hash " << it->second << " -> TEXT";
            need_recreate = true;
        }
    }
    {
        auto it = existing_cols.find("display_name");
        if (it != existing_cols.end() && it->second != "TEXT") {
            INFO(logger) << "Column type changed: oauth_users.display_name " << it->second << " -> TEXT";
            need_recreate = true;
        }
    }
    {
        auto it = existing_cols.find("avatar_url");
        if (it != existing_cols.end() && it->second != "TEXT") {
            INFO(logger) << "Column type changed: oauth_users.avatar_url " << it->second << " -> TEXT";
            need_recreate = true;
        }
    }
    {
        auto it = existing_cols.find("email_verified");
        if (it != existing_cols.end() && it->second != "INTEGER") {
            INFO(logger) << "Column type changed: oauth_users.email_verified " << it->second << " -> INTEGER";
            need_recreate = true;
        }
    }
    {
        auto it = existing_cols.find("enabled");
        if (it != existing_cols.end() && it->second != "INTEGER") {
            INFO(logger) << "Column type changed: oauth_users.enabled " << it->second << " -> INTEGER";
            need_recreate = true;
        }
    }
    {
        auto it = existing_cols.find("create_time");
        if (it != existing_cols.end() && it->second != "TIMESTAMP") {
            INFO(logger) << "Column type changed: oauth_users.create_time " << it->second << " -> TIMESTAMP";
            need_recreate = true;
        }
    }
    {
        auto it = existing_cols.find("update_time");
        if (it != existing_cols.end() && it->second != "TIMESTAMP") {
            INFO(logger) << "Column type changed: oauth_users.update_time " << it->second << " -> TIMESTAMP";
            need_recreate = true;
        }
    }
    if (!need_recreate) {
        for (auto& [name, _] : existing_cols) {
            (void)_;  // suppress unused warning
            bool found = false;
            if (name == "id") found = true;
            if (name == "username") found = true;
            if (name == "email") found = true;
            if (name == "password_hash") found = true;
            if (name == "display_name") found = true;
            if (name == "avatar_url") found = true;
            if (name == "email_verified") found = true;
            if (name == "enabled") found = true;
            if (name == "create_time") found = true;
            if (name == "update_time") found = true;
            if (!found) {
                need_recreate = true;
                WARN(logger) << "Column oauth_users." << name << " removed, table recreate required";
                break;
            }
        }
    }

    if (need_recreate) {
        INFO(logger) << "Recreating table oauth_users";

        std::vector<std::string> common_cols;
        if (existing_cols.find("id") != existing_cols.end()) {
            common_cols.push_back("id");
        }
        if (existing_cols.find("username") != existing_cols.end()) {
            common_cols.push_back("username");
        }
        if (existing_cols.find("email") != existing_cols.end()) {
            common_cols.push_back("email");
        }
        if (existing_cols.find("password_hash") != existing_cols.end()) {
            common_cols.push_back("password_hash");
        }
        if (existing_cols.find("display_name") != existing_cols.end()) {
            common_cols.push_back("display_name");
        }
        if (existing_cols.find("avatar_url") != existing_cols.end()) {
            common_cols.push_back("avatar_url");
        }
        if (existing_cols.find("email_verified") != existing_cols.end()) {
            common_cols.push_back("email_verified");
        }
        if (existing_cols.find("enabled") != existing_cols.end()) {
            common_cols.push_back("enabled");
        }
        if (existing_cols.find("create_time") != existing_cols.end()) {
            common_cols.push_back("create_time");
        }
        if (existing_cols.find("update_time") != existing_cols.end()) {
            common_cols.push_back("update_time");
        }

        if (conn->execute("ALTER TABLE oauth_users RENAME TO oauth_users_tmp")) {
            ERROR(logger) << "RENAME TABLE oauth_users failed";
            return conn->getErrno();
        }
        CreateTableSQLite3(conn);
        if (!common_cols.empty()) {
            std::string cols;
            for (size_t i = 0; i < common_cols.size(); ++i) {
                if (i) cols += ",";
                cols += common_cols[i];
            }
            std::string sql = "INSERT INTO oauth_users (" + cols + ") SELECT " + cols + " FROM oauth_users_tmp";
            if (int rt = conn->execute(sql)) {
                ERROR(logger) << "copy data from oauth_users_tmp to oauth_users failed, errno=" << rt;
                // don't return; try to continue
            }
        }
        conn->execute("DROP TABLE oauth_users_tmp");
        return 0;
    }

    if (existing_cols.find("username") == existing_cols.end()) {
        INFO(logger) << "Adding column oauth_users.username";
        int rt = conn->execute("ALTER TABLE oauth_users ADD COLUMN username TEXT NOT NULL DEFAULT ''");
        if (rt) {
            ERROR(logger) << "ALTER TABLE oauth_users ADD COLUMN username failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("email") == existing_cols.end()) {
        INFO(logger) << "Adding column oauth_users.email";
        int rt = conn->execute("ALTER TABLE oauth_users ADD COLUMN email TEXT NOT NULL DEFAULT ''");
        if (rt) {
            ERROR(logger) << "ALTER TABLE oauth_users ADD COLUMN email failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("password_hash") == existing_cols.end()) {
        INFO(logger) << "Adding column oauth_users.password_hash";
        int rt = conn->execute("ALTER TABLE oauth_users ADD COLUMN password_hash TEXT NOT NULL DEFAULT ''");
        if (rt) {
            ERROR(logger) << "ALTER TABLE oauth_users ADD COLUMN password_hash failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("display_name") == existing_cols.end()) {
        INFO(logger) << "Adding column oauth_users.display_name";
        int rt = conn->execute("ALTER TABLE oauth_users ADD COLUMN display_name TEXT NOT NULL DEFAULT ''");
        if (rt) {
            ERROR(logger) << "ALTER TABLE oauth_users ADD COLUMN display_name failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("avatar_url") == existing_cols.end()) {
        INFO(logger) << "Adding column oauth_users.avatar_url";
        int rt = conn->execute("ALTER TABLE oauth_users ADD COLUMN avatar_url TEXT NOT NULL DEFAULT ''");
        if (rt) {
            ERROR(logger) << "ALTER TABLE oauth_users ADD COLUMN avatar_url failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("email_verified") == existing_cols.end()) {
        INFO(logger) << "Adding column oauth_users.email_verified";
        int rt = conn->execute("ALTER TABLE oauth_users ADD COLUMN email_verified INTEGER NOT NULL DEFAULT 0");
        if (rt) {
            ERROR(logger) << "ALTER TABLE oauth_users ADD COLUMN email_verified failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("enabled") == existing_cols.end()) {
        INFO(logger) << "Adding column oauth_users.enabled";
        int rt = conn->execute("ALTER TABLE oauth_users ADD COLUMN enabled INTEGER NOT NULL DEFAULT 1");
        if (rt) {
            ERROR(logger) << "ALTER TABLE oauth_users ADD COLUMN enabled failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("create_time") == existing_cols.end()) {
        INFO(logger) << "Adding column oauth_users.create_time";
        int rt = conn->execute("ALTER TABLE oauth_users ADD COLUMN create_time TIMESTAMP NOT NULL DEFAULT current_timestamp");
        if (rt) {
            ERROR(logger) << "ALTER TABLE oauth_users ADD COLUMN create_time failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("update_time") == existing_cols.end()) {
        INFO(logger) << "Adding column oauth_users.update_time";
        int rt = conn->execute("ALTER TABLE oauth_users ADD COLUMN update_time TIMESTAMP NOT NULL DEFAULT current_timestamp");
        if (rt) {
            ERROR(logger) << "ALTER TABLE oauth_users ADD COLUMN update_time failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    return 0;
}

int OauthUsersInfoDao::MigrateTableMySQL(chen::IDB::ptr conn) {
    auto data = conn->query("SHOW COLUMNS FROM oauth_users");
    if (!data) {
        ERROR(logger) << "SHOW COLUMNS FROM oauth_users errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    std::map<std::string, std::string> existing_cols;  // name -> type
    while (data->next()) {
        existing_cols[data->getString(0)] = data->getString(1);
    }

    {
        auto it = existing_cols.find("id");
        if (it != existing_cols.end() && it->second != "bigint") {
            INFO(logger) << "Modifying column oauth_users.id " << it->second << " -> bigint";
            int rt = conn->execute("ALTER TABLE oauth_users MODIFY COLUMN `id` bigint NOT NULL DEFAULT 0 COMMENT '主键'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN oauth_users.id failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }
    {
        auto it = existing_cols.find("username");
        if (it != existing_cols.end() && it->second != "varchar(128)") {
            INFO(logger) << "Modifying column oauth_users.username " << it->second << " -> varchar(128)";
            int rt = conn->execute("ALTER TABLE oauth_users MODIFY COLUMN `username` varchar(128) NOT NULL DEFAULT '' COMMENT '用户名'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN oauth_users.username failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }
    {
        auto it = existing_cols.find("email");
        if (it != existing_cols.end() && it->second != "varchar(128)") {
            INFO(logger) << "Modifying column oauth_users.email " << it->second << " -> varchar(128)";
            int rt = conn->execute("ALTER TABLE oauth_users MODIFY COLUMN `email` varchar(128) NOT NULL DEFAULT '' COMMENT '邮箱'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN oauth_users.email failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }
    {
        auto it = existing_cols.find("password_hash");
        if (it != existing_cols.end() && it->second != "varchar(128)") {
            INFO(logger) << "Modifying column oauth_users.password_hash " << it->second << " -> varchar(128)";
            int rt = conn->execute("ALTER TABLE oauth_users MODIFY COLUMN `password_hash` varchar(128) NOT NULL DEFAULT '' COMMENT 'bcrypt 密码哈希'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN oauth_users.password_hash failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }
    {
        auto it = existing_cols.find("display_name");
        if (it != existing_cols.end() && it->second != "varchar(128)") {
            INFO(logger) << "Modifying column oauth_users.display_name " << it->second << " -> varchar(128)";
            int rt = conn->execute("ALTER TABLE oauth_users MODIFY COLUMN `display_name` varchar(128) NOT NULL DEFAULT '' COMMENT '显示名称'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN oauth_users.display_name failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }
    {
        auto it = existing_cols.find("avatar_url");
        if (it != existing_cols.end() && it->second != "varchar(128)") {
            INFO(logger) << "Modifying column oauth_users.avatar_url " << it->second << " -> varchar(128)";
            int rt = conn->execute("ALTER TABLE oauth_users MODIFY COLUMN `avatar_url` varchar(128) NOT NULL DEFAULT '' COMMENT '头像 URL'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN oauth_users.avatar_url failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }
    {
        auto it = existing_cols.find("email_verified");
        if (it != existing_cols.end() && it->second != "int") {
            INFO(logger) << "Modifying column oauth_users.email_verified " << it->second << " -> int";
            int rt = conn->execute("ALTER TABLE oauth_users MODIFY COLUMN `email_verified` int NOT NULL DEFAULT 0 COMMENT '邮箱是否已验证'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN oauth_users.email_verified failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }
    {
        auto it = existing_cols.find("enabled");
        if (it != existing_cols.end() && it->second != "int") {
            INFO(logger) << "Modifying column oauth_users.enabled " << it->second << " -> int";
            int rt = conn->execute("ALTER TABLE oauth_users MODIFY COLUMN `enabled` int NOT NULL DEFAULT 1 COMMENT '是否启用'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN oauth_users.enabled failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }
    {
        auto it = existing_cols.find("create_time");
        if (it != existing_cols.end() && it->second != "timestamp") {
            INFO(logger) << "Modifying column oauth_users.create_time " << it->second << " -> timestamp";
            int rt = conn->execute("ALTER TABLE oauth_users MODIFY COLUMN `create_time` timestamp NOT NULL DEFAULT current_timestamp COMMENT '创建时间'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN oauth_users.create_time failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }
    {
        auto it = existing_cols.find("update_time");
        if (it != existing_cols.end() && it->second != "timestamp") {
            INFO(logger) << "Modifying column oauth_users.update_time " << it->second << " -> timestamp";
            int rt = conn->execute("ALTER TABLE oauth_users MODIFY COLUMN `update_time` timestamp NOT NULL DEFAULT current_timestamp COMMENT '更新时间'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN oauth_users.update_time failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }

    for (auto& [name, _] : existing_cols) {
        (void)_;
        bool found = false;
        if (name == "id") found = true;
        if (name == "username") found = true;
        if (name == "email") found = true;
        if (name == "password_hash") found = true;
        if (name == "display_name") found = true;
        if (name == "avatar_url") found = true;
        if (name == "email_verified") found = true;
        if (name == "enabled") found = true;
        if (name == "create_time") found = true;
        if (name == "update_time") found = true;
        if (!found) {
            WARN(logger) << "Dropping column oauth_users." << name << " (not in schema, data will be lost)";
            int rt = conn->execute("ALTER TABLE oauth_users DROP COLUMN `" + name + "`");
            if (rt) {
                ERROR(logger) << "DROP COLUMN oauth_users." << name << " failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }

    if (existing_cols.find("username") == existing_cols.end()) {
        INFO(logger) << "Adding column oauth_users.username";
        int rt = conn->execute("ALTER TABLE oauth_users ADD COLUMN `username` varchar(128) NOT NULL DEFAULT '' COMMENT '用户名'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE oauth_users ADD COLUMN username failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("email") == existing_cols.end()) {
        INFO(logger) << "Adding column oauth_users.email";
        int rt = conn->execute("ALTER TABLE oauth_users ADD COLUMN `email` varchar(128) NOT NULL DEFAULT '' COMMENT '邮箱'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE oauth_users ADD COLUMN email failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("password_hash") == existing_cols.end()) {
        INFO(logger) << "Adding column oauth_users.password_hash";
        int rt = conn->execute("ALTER TABLE oauth_users ADD COLUMN `password_hash` varchar(128) NOT NULL DEFAULT '' COMMENT 'bcrypt 密码哈希'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE oauth_users ADD COLUMN password_hash failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("display_name") == existing_cols.end()) {
        INFO(logger) << "Adding column oauth_users.display_name";
        int rt = conn->execute("ALTER TABLE oauth_users ADD COLUMN `display_name` varchar(128) NOT NULL DEFAULT '' COMMENT '显示名称'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE oauth_users ADD COLUMN display_name failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("avatar_url") == existing_cols.end()) {
        INFO(logger) << "Adding column oauth_users.avatar_url";
        int rt = conn->execute("ALTER TABLE oauth_users ADD COLUMN `avatar_url` varchar(128) NOT NULL DEFAULT '' COMMENT '头像 URL'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE oauth_users ADD COLUMN avatar_url failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("email_verified") == existing_cols.end()) {
        INFO(logger) << "Adding column oauth_users.email_verified";
        int rt = conn->execute("ALTER TABLE oauth_users ADD COLUMN `email_verified` int NOT NULL DEFAULT 0 COMMENT '邮箱是否已验证'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE oauth_users ADD COLUMN email_verified failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("enabled") == existing_cols.end()) {
        INFO(logger) << "Adding column oauth_users.enabled";
        int rt = conn->execute("ALTER TABLE oauth_users ADD COLUMN `enabled` int NOT NULL DEFAULT 1 COMMENT '是否启用'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE oauth_users ADD COLUMN enabled failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("create_time") == existing_cols.end()) {
        INFO(logger) << "Adding column oauth_users.create_time";
        int rt = conn->execute("ALTER TABLE oauth_users ADD COLUMN `create_time` timestamp NOT NULL DEFAULT current_timestamp COMMENT '创建时间'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE oauth_users ADD COLUMN create_time failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("update_time") == existing_cols.end()) {
        INFO(logger) << "Adding column oauth_users.update_time";
        int rt = conn->execute("ALTER TABLE oauth_users ADD COLUMN `update_time` timestamp NOT NULL DEFAULT current_timestamp COMMENT '更新时间'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE oauth_users ADD COLUMN update_time failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    return 0;
}


} //namespace data
} //namespace auth
