/**
 * @file oauth_clients_info.h
 * @brief OAuth 客户端注册表
 * @note Auto-generated by ORM code generator. DO NOT MODIFY.
 */
#pragma once

#include <vector>

#include <chen/db/db.h>
#include <chen/db/query_builder.h>
#include <chen/util/util.h>

namespace auth {
namespace data {

class OauthClientsInfoDao;
/**
 * @brief OAuth 客户端注册表
 */
class OauthClientsInfo {
friend class OauthClientsInfoDao;
public:
    typedef std::shared_ptr<OauthClientsInfo> ptr;

    OauthClientsInfo();

    /**
     * @brief 获取主键
     * @return 主键
     */
    const int64_t& getId() { return m_id; }
    /**
     * @brief 设置主键
     * @param v 主键
     */
    void setId(const int64_t& v);

    /**
     * @brief 获取客户端 ID
     * @return 客户端 ID
     */
    const std::string& getClientId() { return m_clientId; }
    /**
     * @brief 设置客户端 ID
     * @param v 客户端 ID
     */
    void setClientId(const std::string& v);

    /**
     * @brief 获取client_secret 的 bcrypt 哈希
     * @return client_secret 的 bcrypt 哈希
     */
    const std::string& getClientSecretHash() { return m_clientSecretHash; }
    /**
     * @brief 设置client_secret 的 bcrypt 哈希
     * @param v client_secret 的 bcrypt 哈希
     */
    void setClientSecretHash(const std::string& v);

    /**
     * @brief 获取客户端名称
     * @return 客户端名称
     */
    const std::string& getClientName() { return m_clientName; }
    /**
     * @brief 设置客户端名称
     * @param v 客户端名称
     */
    void setClientName(const std::string& v);

    /**
     * @brief 获取回调 URI 白名单（JSON 数组）
     * @return 回调 URI 白名单（JSON 数组）
     */
    const std::string& getRedirectUris() { return m_redirectUris; }
    /**
     * @brief 设置回调 URI 白名单（JSON 数组）
     * @param v 回调 URI 白名单（JSON 数组）
     */
    void setRedirectUris(const std::string& v);

    /**
     * @brief 获取允许的 grant_type
     * @return 允许的 grant_type
     */
    const std::string& getGrantTypes() { return m_grantTypes; }
    /**
     * @brief 设置允许的 grant_type
     * @param v 允许的 grant_type
     */
    void setGrantTypes(const std::string& v);

    /**
     * @brief 获取允许的 scope 列表
     * @return 允许的 scope 列表
     */
    const std::string& getAllowedScopes() { return m_allowedScopes; }
    /**
     * @brief 设置允许的 scope 列表
     * @param v 允许的 scope 列表
     */
    void setAllowedScopes(const std::string& v);

    /**
     * @brief 获取客户端主页
     * @return 客户端主页
     */
    const std::string& getClientUri() { return m_clientUri; }
    /**
     * @brief 设置客户端主页
     * @param v 客户端主页
     */
    void setClientUri(const std::string& v);

    /**
     * @brief 获取客户端图标
     * @return 客户端图标
     */
    const std::string& getLogoUri() { return m_logoUri; }
    /**
     * @brief 设置客户端图标
     * @param v 客户端图标
     */
    void setLogoUri(const std::string& v);

    /**
     * @brief 获取是否启用
     * @return 是否启用
     */
    const int32_t& getEnabled() { return m_enabled; }
    /**
     * @brief 设置是否启用
     * @param v 是否启用
     */
    void setEnabled(const int32_t& v);

    /**
     * @brief 获取创建时间
     * @return 创建时间
     */
    const int64_t& getCreateTime() { return m_createTime; }
    /**
     * @brief 设置创建时间
     * @param v 创建时间
     */
    void setCreateTime(const int64_t& v);

    /**
     * @brief 获取更新时间
     * @return 更新时间
     */
    const int64_t& getUpdateTime() { return m_updateTime; }
    /**
     * @brief 设置更新时间
     * @param v 更新时间
     */
    void setUpdateTime(const int64_t& v);

    /**
     * @brief 转为 JSON 字符串
     * @return JSON 字符串
     */
    std::string toJsonString() const;

    /** @brief 清除脏标记（Update 成功后自动调用） */
    void markClean() { m_flags = 0; }
    /**
     * @brief 是否有字段被修改过
     * @return true 有未保存的修改，false 无修改
     */
    bool isDirty() const { return m_flags != 0; }

private:
    int32_t m_enabled;
    int64_t m_id;
    std::string m_clientId;
    std::string m_clientSecretHash;
    std::string m_clientName;
    std::string m_grantTypes;
    std::string m_allowedScopes;
    std::string m_clientUri;
    std::string m_logoUri;
    std::string m_redirectUris;
    int64_t m_createTime;
    int64_t m_updateTime;
    uint64_t m_flags = 0;
};


class OauthClientsInfoDao {
public:
    typedef std::shared_ptr<OauthClientsInfoDao> ptr;
    static int Update(OauthClientsInfo::ptr info, chen::IDB::ptr conn);
    static int Insert(OauthClientsInfo::ptr info, chen::IDB::ptr conn);
    static int InsertOrUpdate(OauthClientsInfo::ptr info, chen::IDB::ptr conn);
    static int BatchInsert(const std::vector<OauthClientsInfo::ptr>& infos, chen::IDB::ptr conn);
    static int BatchUpdate(const std::vector<OauthClientsInfo::ptr>& infos, chen::IDB::ptr conn);
    static int BatchDelete(const std::vector<int64_t>& ids, chen::IDB::ptr conn);
    static int Delete(OauthClientsInfo::ptr info, chen::IDB::ptr conn);
    static int Delete(const int64_t& id, chen::IDB::ptr conn);
    static int DeleteById( const int64_t& id, chen::IDB::ptr conn);
    static int DeleteByClientId( const std::string& client_id, chen::IDB::ptr conn);
    static int QueryAll(std::vector<OauthClientsInfo::ptr>& results, chen::IDB::ptr conn);
    static OauthClientsInfo::ptr Query( const int64_t& id, chen::IDB::ptr conn);
    static OauthClientsInfo::ptr QueryByClientId( const std::string& client_id, chen::IDB::ptr conn);
    static int CreateTableSQLite3(chen::IDB::ptr info);
    static int CreateTableMySQL(chen::IDB::ptr info);
    static int MigrateTableSQLite3(chen::IDB::ptr info);
    static int MigrateTableMySQL(chen::IDB::ptr info);
    static int Migrate(chen::IDB::ptr conn);
    static OauthClientsInfo::ptr ParseRow(chen::ISQLData::ptr data);
    static int QueryByBuilder(std::vector<OauthClientsInfo::ptr>& results, chen::QueryBuilder::ptr qb, chen::IDB::ptr conn);
    static int QueryByBuilderPages(std::vector<OauthClientsInfo::ptr>& results, int64_t& total, chen::QueryBuilder::ptr qb, int32_t offset, int32_t limit, chen::IDB::ptr conn);
};

} //namespace data
} //namespace auth
